### ISSUE TITLE
Crash when using an infestation purifier

### ISSUE THREAD

**Issue by ImpulsiveLass** [TeamPeril/Sculk-Hoard#2]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-04-24 20:02:37
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_49966_()" because the return value of "com.github.sculkhorde.common.block.BlockInfestation.InfestationConversionHandler$InfestationTable.getNormalVariant(net.minecraft.world.level.block.state.BlockState)" is null
	at com.github.sculkhorde.common.block.BlockInfestation.InfestationConversionHandler.deinfectBlock(InfestationConversionHandler.java:129) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at com.github.sculkhorde.common.entity.infection.CursorSurfacePurifierEntity.transformBlock(CursorSurfacePurifierEntity.java:50) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at com.github.sculkhorde.common.entity.infection.CursorInfectorEntity.m_8119_(CursorInfectorEntity.java:252) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:671) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.github.sculkhorde.common.block.BlockInfestation.InfestationConversionHandler.deinfectBlock(InfestationConversionHandler.java:129) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at com.github.sculkhorde.common.entity.infection.CursorSurfacePurifierEntity.transformBlock(CursorSurfacePurifierEntity.java:50) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at com.github.sculkhorde.common.entity.infection.CursorInfectorEntity.m_8119_(CursorInfectorEntity.java:252) ~[sculkhorde-1.19.4-0.5.4.jar%23149!/:1.19.4-0.5.4] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:671) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: sculkhorde:cursor_surface_purifier (com.github.sculkhorde.common.entity.infection.CursorSurfacePurifierEntity)
	Entity ID: 50445
	Entity Name: entity.sculkhorde.cursor_surface_purifier
	Entity's Exact location: 150.00, -34.00, -379.00
	Entity's Block location: World: (150,-34,-379), Section: (at 6,14,5 in 9,-3,-24; chunk contains blocks 144,-64,-384 to 159,319,-369), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:485) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:325) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:305) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['ImpulsiveLad0955'/19207, l='ServerLevel[benis]', x=149.30, y=-29.75, z=-376.55]]
	Chunk stats: 3721
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,68,-368), Section: (at 0,4,0 in 11,4,-23; chunk contains blocks 176,-64,-368 to 191,319,-353), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 139913 game time, 139913 day time
	Level name: benis
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 25089 (now: false), thunder time: 30056 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:896) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:817) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:664) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23150!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5813552720 bytes (5544 MiB) / 9361686528 bytes (8928 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Radeon RX 580 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: DriverVersion=31.0.14043.1000
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 75195.73
	Virtual memory used (MB): 24768.72
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 3.22
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['ImpulsiveLad0955'/19207, l='ServerLevel[benis]', x=149.30, y=-29.75, z=-376.55]]
	Data Packs: vanilla, mod:forge, mod:geckolib (incompatible), mod:sculkhorde (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.4-forge-45.0.49
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.49.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.49.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.49.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.49.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.49.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.19.4-45.0.49-universal.jar                |Forge                         |forge                         |45.0.49             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		geckolib-forge-1.19.4-4.1.3.jar                   |GeckoLib 4                    |geckolib                      |4.1.3               |DONE      |Manifest: NOSIGNATURE
		sculkhorde-1.19.4-0.5.4.jar                       |Sculk Horde                   |sculkhorde                    |1.19.4-0.5.4        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a37a177c-5e8f-4faf-ad75-a2f4f019710b
	FML: 45.0
	Forge: net.minecraftforge:45.0.49

**Comment by Mikeatron-User** [comment]
This Bug has been resolved in version 1.19.4-0.5.5. Thank you for reporting
