### ISSUE TITLE
Funny Sculk Ravager Crash [1.20.1]

### ISSUE THREAD

**Issue by Cephelo** [TeamPeril/Sculk-Hoard#75]
Here's the crash stacktrace from the log:
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Ravager.m_8024_(Ravager.java:2172)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.common.entity.SculkRavagerEntity.m_8024_(SculkRavagerEntity.java:192)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_6140_(Mob.java:768)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2548)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8107_(Mob.java:536)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Monster.m_8107_(Monster.java:42)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.raid.Raider.m_8107_(Raider.java:114)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.monster.Ravager.m_8107_(Ravager.java:132)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.PathfinderMob.m_8119_(PathfinderMob.java:652)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.observable$track(ServerLevel.java:14669)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.redirect$hkd000$observable$onTickNonPassenger(ServerLevel.java:14685)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$182(Level.java)
	at TRANSFORMER/neruina@2.1.2/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$foj000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:9540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Unknown Source)

Something with the customServerAiStep method, though unfortunately I'm not too sure of the exact cause.  It seems to occur randomly when there's a couple Sculk Ravagers around?

I have not dismissed the possibility that it could be a mixing conflict either, so let me know if there's any way I can help.
No crash report since I've got Neruina.  Full Log is here, but it's a big one: 
[latest.log](https://github.com/user-attachments/files/17609473/latest.log)

**Comment by Mikeatron-User** [comment]
A very odd crash report. Unfortunately, the crash report doesn't exactly tell me what could be causing it. I'm going to assume this is a mod conflict issue given the nature of it.

**Comment by ScreamingMC** [comment]
First, you still haven't fixed the ravager, the bug is still there even in newer versions. Second, why are you blaming others that it's their own fault instead of actually checking if it's not actually yours?

classic human behavior: blaming others before checking ourselves
