### ISSUE TITLE
Incompatibility with Dimensional Threading Reforked

### ISSUE THREAD

**Issue by Cephelo** [TeamPeril/Sculk-Hoard#79]
It seems whenever I'm outside of the overworked with DTR installed, I continuously get this error in the logs, though no crash occurs:
```
[dimthread_server_overworld/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "com.github.sculkhorde.common.block.InfestationEntries.ITagInfestedBlockEntity.setNormalBlockState(net.minecraft.world.level.block.state.BlockState)" because the return value of "com.github.sculkhorde.common.block.InfestationEntries.ITagInfestedBlock.getTagInfestedBlockEntity(net.minecraft.world.level.Level, net.minecraft.core.BlockPos)" is null
	Index: 21
	Listeners:
		0: HIGH
		1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		2: NORMAL
		3: ASM: class com.hostilevillages.event.EventHandler addToWorld(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		4: ASM: class tictim.paraglider.forge.event.WindEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		5: ASM: class bl4ckscor3.mod.snowundertrees.LevelTickHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		6: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@c8f5d6b
		7: ASM: class com.izofar.takesapillage.event.ModEntityEvents checkForUnSpawnedGolem(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		8: ASM: class com.dragonfight.event.EventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		9: ASM: class com.izofar.takesapillage.event.ModWorldEvents onSpecialSpawn(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		10: ASM: class net.mcreator.spelunkerscharm.procedures.WorldTickHandlerProcedure onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		11: ASM: com.mrcrayfish.framework.event.ForgeEvents@c6da1ca onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		12: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@288d6a84
		13: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@383acc4e
		14: ASM: com.corosus.mobtimizations.loader.forge.MobtimizationsForge@33e7a2bd worldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		15: ASM: class io.redspace.ironsspellbooks.effect.guiding_bolt.GuidingBoltManager serverTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		16: ASM: class net.silentchaos512.scalinghealth.event.DifficultyEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		17: ASM: INSTANCE onLevelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		18: ASM: com.github.alexthe668.domesticationinnovation.client.ClientProxy@43bf6d06 onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		19: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@5771966f
		20: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		21: ASM: class com.github.sculkhorde.util.ForgeEventSubscriber WorldTickEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		22: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@21e3edef
		23: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@62f97a1d
		24: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@c4f82b0
		25: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onServerTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		26: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@57d6afb8
		27: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@6964bc38
		28: ASM: dev.shadowsoffire.apotheosis.adventure.boss.BossEvents@65c3cbf9 tick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		29: ASM: com.illusivesoulworks.polymorph.common.CommonEventsListener@73dab645 levelTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		30: ASM: com.foopy.forgeskyboxes.SkyboxManager@7458f072 onEndTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		31: net.minecraftforge.eventbus.EventBus$$Lambda$2012/0x0000000800a37620@40640a9b
		32: ASM: class net.silentchaos512.lib.util.EntityHelper onWorldTick(Lnet/minecraftforge/event/TickEvent;)V
		33: ASM: me.lucko.spark.forge.ForgeTickHook@31b44b50 onTick(Lnet/minecraftforge/event/TickEvent;)V
		34: ASM: me.lucko.spark.forge.ForgeTickReporter@4f0c210e onTick(Lnet/minecraftforge/event/TickEvent;)V
		35: ASM: me.lucko.spark.forge.ForgeTickHook@62402eb4 onTick(Lnet/minecraftforge/event/TickEvent;)V
		36: ASM: me.lucko.spark.forge.ForgeTickReporter@4850b3fd onTick(Lnet/minecraftforge/event/TickEvent;)V
		37: LOWEST
		38: ASM: class net.mehvahdjukaar.snowyspirit.wreath_stuff.ServerEvents tickEvent(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
		39: ASM: class betterdays.event.ServerEventListener onWorldTick(Lnet/minecraftforge/event/TickEvent$LevelTickEvent;)V
java.lang.NullPointerException: Cannot invoke "com.github.sculkhorde.common.block.InfestationEntries.ITagInfestedBlockEntity.setNormalBlockState(net.minecraft.world.level.block.state.BlockState)" because the return value of "com.github.sculkhorde.common.block.InfestationEntries.ITagInfestedBlock.getTagInfestedBlockEntity(net.minecraft.world.level.Level, net.minecraft.core.BlockPos)" is null
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.common.block.InfestationEntries.BlockInfestationTable.infectBlock(BlockInfestationTable.java:149)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.util.BlockInfestationHelper.tryToInfestBlock(BlockInfestationHelper.java:209)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.common.entity.infection.CursorSurfaceInfectorEntity.transformBlock(CursorSurfaceInfectorEntity.java:69)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.common.entity.infection.CursorEntity.exploreTick(CursorEntity.java:259)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.common.entity.infection.CursorEntity.cursorTick(CursorEntity.java:348)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.core.gravemind.CursorHandler.tickCursors(CursorHandler.java:67)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.core.gravemind.CursorHandler.serverTick(CursorHandler.java:103)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.util.ForgeEventSubscriber.WorldTickEvent(ForgeEventSubscriber.java:97)
	at TRANSFORMER/sculkhorde@1.20.1-0.9.16/com.github.sculkhorde.util.__ForgeEventSubscriber_WorldTickEvent_LevelTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md813f9a$dimthread$lambda$tickWorlds$0$a(MinecraftServer.java:10892)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.DimThread.swapThreadsAndRun(DimThread.java:50)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.md813f9a$dimthread$lambda$tickWorlds$1$9(MinecraftServer.java:10891)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$1(ThreadPool.java:54)
	at TRANSFORMER/dimthread@1.0.5/me.srrapero720.dimthread.thread.ThreadPool.lambda$execute$0(ThreadPool.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

A simple null check may be enough to fix this, though I could be wrong.

**Comment by Mikeatron-User** [comment]
While a null check could fix this, the fact were getting a null error at all is concerning. I suspect the multi threading interferes with the Gravemind working in all dimensions. I'll investigate this further, but I suspect this mod is incompatible with how I've built the Gravemind.
